name: "vue cli plugin s3 deploy next action"
description: "A Github action for vue-cli-plugin-s3-deploy-next"
author: techouse
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: green
